# Generated by Django 5.0.4 on 2024-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_objective', models.TextField()),
                ('leading_indicator', models.TextField()),
                ('user_outcomes', models.TextField()),
                ('model_properties', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('status_penyelesaian', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automate', models.TextField()),
                ('prompt', models.TextField()),
                ('organization', models.TextField()),
                ('annotate', models.TextField()),
                ('achieve_system', models.TextField()),
                ('minimize_flaws', models.TextField()),
                ('data_grown_system', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntImp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proses_bisnis', models.TextField()),
                ('teknologi_dipakai', models.TextField()),
                ('sistem_cerdas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kendala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah_pengembangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerImp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelaksanaan_deployment', models.TextField()),
                ('pemeliharaan_sistem', models.TextField()),
                ('pelaksanaan_operasi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
    ]
