# Generated by Django 5.0.4 on 2024-07-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_objective', models.TextField(null=True)),
                ('leading_indicator', models.TextField(null=True)),
                ('user_outcomes', models.TextField(null=True)),
                ('model_properties', models.TextField(null=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('status_penyelesaian', models.TextField()),
                ('projek', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_intel.dataprojek')),
            ],
        ),
        migrations.CreateModel(
            name='IntExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automate', models.TextField(null=True)),
                ('prompt', models.TextField(null=True)),
                ('organization', models.TextField(null=True)),
                ('annotate', models.TextField(null=True)),
                ('achieve_system', models.TextField()),
                ('minimize_flaws', models.TextField()),
                ('data_grown_system', models.TextField()),
                ('projek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_intel.dataprojek')),
            ],
        ),
        migrations.CreateModel(
            name='IntImp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proses_bisnis', models.TextField()),
                ('teknologi_dipakai', models.TextField()),
                ('sistem_cerdas', models.TextField()),
                ('projek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_intel.dataprojek')),
            ],
        ),
        migrations.CreateModel(
            name='Kendala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah_pengembangan', models.TextField()),
                ('projek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_intel.dataprojek')),
            ],
        ),
        migrations.CreateModel(
            name='PerImp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelaksanaan_deployment', models.TextField()),
                ('pemeliharaan_sistem', models.TextField()),
                ('pelaksanaan_operasi', models.TextField()),
                ('projek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_intel.dataprojek')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_project', models.CharField(max_length=100)),
                ('tujuan_project', models.CharField(max_length=1000)),
                ('tangmul_project', models.DateField()),
                ('tangsel_project', models.DateField()),
                ('pic_project', models.CharField(max_length=40)),
                ('status_project', models.TextField()),
                ('biaya', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('projek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='data_intel.dataprojek')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('projek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_intel.dataprojek')),
            ],
        ),
    ]
